# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  testproj-app1:
    image: testproj
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://testproj-postgresql1:5432/testprojdb
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://testproj-postgresql1:5432/testprojdb
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  
    ports:
      - 127.0.0.1:9020:8080
  testproj-app2:
    image: testproj
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://testproj-postgresql2:5433/testprojdb
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://testproj-postgresql2:5433/testprojdb
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 127.0.0.1:9021:8080

  testproj-postgresql1:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=testprojdb
      - POSTGRES_USER=testproj_dbuser
      - POSTGRES_PASSWORD=q!NDTcV7dyIS!W@+
    ports:
      - 127.0.0.1:5432:5432
      
  testproj-postgresql2:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=testprojdb
      - POSTGRES_USER=testproj_dbuser
      - POSTGRES_PASSWORD=q!NDTcV7dyIS!W@+
    ports:
        - 127.0.0.1:5433:5432

  testproj-ws1:
    build: ./nginx
    ports:
      - 80:80
    restart: always
   
  testproj-ws2:
    build: ./nginx
    ports:
      - 81:80
    restart: always
    
  testproj-ws3:
    build: ./nginx
    ports:
      - 82:80
    restart: always
    
  testproj-smtp:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.testproj.com
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_RSPAMD=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
    restart: always
  